# @package _global_

####NOTE####
# *- Need to modify points_cls_loss when change query init.
model:
  type: IAScene
  view_scales: [4, 8, 16]
  embed_dims: 128
  encoder:
    type: MMDetWrapper
    config_path: maskdino/configs/maskdino_r50_8xb2-panoptic-export.py
    custom_imports: maskdino
    checkpoint_path: pretrain/maskdino_r50_50e_300q_panoptic_pq53.0.pth
  
  bevpipeline:
    type: BEVFeature
    in_channels: 128
    encoder:
      type: SparseUNet
      in_c: 128
    bev_seg: True


  decoder:
    type: IASceneDecoder
    embed_dims: 128
    ins_layers: 3 # TEMP
    bk_layers: 3

  criterions: [sem_scal, geo_scal, ce_ssc, bev_seg, geo_h, depth]

optimizer:
  paramwise_cfg:
    - name: encoder.model
      lr_mult: 0.1 # original_ 0.1

