# @package _global_

data:
  datasets:
    type: KITTI360
    splits: [train, val, test]
    data_root: /mnt/A/hust_ley/Dataset_LEY/SSCBench/kitti360/dataset
    label_root: /mnt/A/hust_ley/Dataset_LEY/SSCBench/kitti360/dataset/labels
    depth_root: /mnt/A/hust_ley/Dataset_LEY/SSCBench/kitti360/dataset/depth
    data_config:
      input_size: [384, 1408]
      resize: [0., 0.]
      rot: [0.0, 0.0]
      flip: False
      crop_h: [0.0, 0.0]
      resize_test: 0.00
    frustum_size: 8
  loader:
    batch_size: 1
    num_workers: 4

model:
  image_shape: [384, 1408]
  scene_size: [256, 256, 32]
  volume_scale: 2
  num_classes: 19
  class_frequencies: [
        2264087502, 20098728, 104972, 96297, 1149426, 
        4051087, 125103, 105540713, 16292249, 45297267,
        14454132, 110397082, 6766219, 295883213, 50037503, 
        1561069, 406330, 30516166, 1950115]
  
  decoder:
    bk_cls: 10 # empty + ['road', 'parking', 'sidewalk', 'other-ground', 'building', 'fence', 'vegetation', 'terrain', 'other-structure']
    ins_cls: 10 # empty + ['car', 'bicycle', 'motorcycle', 'truck', 'other-vehicle', 'person', 'pole', 'traffic-sign', 'other-object']
    feats_shape: [24, 88] 
evaluator:
  type: SSCMetrics
  num_classes: 19
