# @package _global_
data:
  datasets:
    type: SemanticKITTI
    splits: [train, val, test]
    data_root: /mnt/A/hust_ley/Dataset_LEY/semantic_kitti
    label_root: /mnt/A/hust_ley/Dataset_LEY/semantic_kitti/dataset/labels
    depth_root: /mnt/A/hust_ley/Dataset_LEY/semantic_kitti/dataset/depth
    data_config:
      input_size: [384, 1280]
      resize: [0., 0.]
      rot: [0.0, 0.0]
      flip: False
      crop_h: [0.0, 0.0]
      resize_test: 0.00
    frustum_size: 8
  loader:
    batch_size: 1
    num_workers: 4

model:
  image_shape: [384, 1280]
  scene_size: [256, 256, 32]
  volume_scale: 2
  num_classes: 20
  class_frequencies: [
        5.41773033e09, 1.57835390e07, 1.25136000e05, 1.18809000e05, 6.46799000e05,
        8.21951000e05, 2.62978000e05, 2.83696000e05, 2.04750000e05, 6.16887030e07,
        4.50296100e06, 4.48836500e07, 2.26992300e06, 5.68402180e07, 1.57196520e07,
        1.58442623e08, 2.06162300e06, 3.69705220e07, 1.15198800e06, 3.34146000e05,
    ]
  
  decoder:
    bk_cls: 10 # empty + ['road', 'parking', 'sidewalk', 'other-ground', 'building', 'fence', 'vegetation', 'trunk', 'terrain']
    ins_cls: 11 # empty + ['car', 'bicycle', 'motorcycle', 'truck', 'other-vehicle', 'person', 'bicyclist', 'motorcyclist', 'pole', 'traffic-sign']
    feats_shape: [24, 80]
evaluator:
  type: SSCMetrics
  num_classes: 20
